package com.appstud.testappstud.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemDaoConfig;

    private final MyContactDao myContactDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemDaoConfig = daoConfigMap.get(MyContactDao.class).clone();
        itemDaoConfig.initIdentityScope(type);


        myContactDao = new MyContactDao(itemDaoConfig, this);

        registerDao(MyContact.class, myContactDao);
    }
    
    public void clear() {
        itemDaoConfig.getIdentityScope().clear();
    }

    public MyContactDao getMyContactDao() {
        return myContactDao;
    }


}
